#High-priority Order #3

#Number of orders:
#Number of shipments per order: 1
#Challenges:
#  -Interruption: Yes
#  -Drop parts: No
#  -Sensor blackout: No
#  -Part flipping: Yes
#  -Faulty parts: Yes
#  -Moving obstacle: No
#Containers
# -Belt: Yes
# -Bins: Yes
# -Shelf: no
#AGV
# -order_0:
#   -shipment_0: agv2
# -order_1:
#   -shipment_0: agv1
#Time limit: 500

time_limit: 500

options:
  gazebo_state_logging: true
  insert_models_over_bins: true
  insert_models_over_shelves: true
  belt_population_cycles: 10
  spawn_extra_models: true
  model_type_aliases:
    order_part1: pulley_part_blue
    order_part2: gear_part_green
    order_part3: disk_part_blue
    order_part1: pulley_part_red

shelf_layout:
  row_1: ['base',0,'base','base'] #shelves: 3, 4, 5
  row_2: ['pipe','base',0,'base']   #shelves: 6, 7, 8
  row_3: ['base','pipe',0,'collar'] #shelves: 9, 10, 11


orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 1
    destinations: [agv2]
    products:
      part_0:
        type: pulley_part_red
        pose:
          xyz: [0.0, 0.0, 0]
          rpy: [0, 0, 0]
      part_1:
        type: gear_part_green
        pose:
          xyz: [0.15, 0.2, 0]
          rpy: [0, 0, 0]
      part_2:
        type: disk_part_blue
        pose:
          xyz: [0.15, -0.2, 0]
          rpy: [0, 0, 0]
      part_3:
        type: pulley_part_red
        pose:
          xyz: [-0.15, -0.2, 0]
          rpy: ['pi', 0, 0]
  order_1:
    announcement_condition: wanted_products
    announcement_condition_value: 1
    shipment_count: 1
    destinations: [agv1]
    products:
      part_0:
        type: pulley_part_red
        pose:
          xyz: [-0.12, -0.2, 0]
          rpy: ['pi', 0, 0]
      part_1:
        type: pulley_part_blue
        pose:
          xyz: [0.12, 0.2, 0]
          rpy: ['pi', 0, 0]
      part_2:
        type: gear_part_green
        pose:
          xyz: [0.0, 0.0, 0]
          rpy: [0, 0, 0]
      part_3:
        type: pulley_part_red
        pose:
          xyz: [-0.15, 0.2, 0]
          rpy: [0, 0, 0]
      part_4:
        type: disk_part_blue
        pose:
          xyz: [0.15, -0.2, 0]
          rpy: [0, 0, 0]

models_over_bins:
  bin1:
    models:
      gear_part_green:
        xyz_start: [0.2, 0.1, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2
  bin11:
    models:
      gear_part_green:
        xyz_start: [0.2, 0.1, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2
  bin2:
    models:
      disk_part_blue:
        xyz_start: [0.28, 0.2, 0.0]
        xyz_end: [0.28, 0.4, 0.0]
        rpy: [0, 0, 0.28]
        num_models_x: 1
        num_models_y: 2
  bin12:
    models:
      disk_part_blue:
        xyz_start: [0.28, 0.2, 0.0]
        xyz_end: [0.28, 0.4, 0.0]
        rpy: [0, 0, 0.28]
        num_models_x: 1
        num_models_y: 2


belt_models:
  pulley_part_blue:
    10.0:
      pose:
        xyz: [0.0, 4.3, 0.92]
        rpy: [0, 0, 0]

#2 arms advantageous
models_over_shelves:
  shelf2:
    models:
      pulley_part_red:
        xyz_start: [1, -0.45, 0.0]
        xyz_end: [0., -0.45, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 1
  shelf1:
    models:
      pulley_part_red:
        xyz_start: [1, 0.35, 0.0]
        xyz_end: [0., 0.35, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 1



#Faulty products
faulty_products:
  - disk_part_blue_1
  - pulley_part_red_1
  - pulley_part_red_4
