#Moving Obstacle #4

#Number of orders: 1
#Number of shipments per order: 1
#Challenges:
#  -Interruption: no
#  -Drop parts: Yes
#  -Sensor blackout: No
#  -Part flipping: Yes
#  -Faulty parts: Yes
#  -Moving obstacle: Yes
#Containers
# -Belt: Yes
# -Bins: Optional
# -Shelf: Yes
#AGV
# -order_0:
#   -shipment_0: agv1
#   -shipment_1: agv2
#Time limit: Yes

time_limit: 500

options:
  gazebo_state_logging: true
  insert_models_over_bins: true
  insert_models_over_shelves: true
  belt_population_cycles: 15 #How many objects to spawn in total
  spawn_extra_models: true
  model_type_aliases:
    order_part1: gasket_part_green
    order_part2: gasket_part_blue
    order_part3: gear_part_blue
    order_part4: pulley_part_red

shelf_layout:
  row_1: ['base','base',0,'base'] #shelves: 3, 4, 5
  row_2: ['pipe','base',0,'base']   #shelves: 6, 7, 8
  row_3: ['base','collar',0,'collar'] #shelves: 9, 10, 11

aisle_layout:
  person_1:
    location: 4.57
    start_time: 16.
    move_time: 9.
    wait_time: 7.
  person_2:
    location: 1.57
    start_time: 0.
    move_time: 9.
    wait_time: 7.


orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 2
    destinations: [agv1,agv2]
    products:
      part_0:
        type: pulley_part_red
        pose:
          xyz: [0.10, 0.2, 0.2]
          rpy: [0, 0, 0]
      part_1:
        type: gasket_part_green
        pose:
          xyz: [0.0, 0.0, 0.2]
          rpy: [0, 0, '-pi/4']
#      part_2:
#        type: gasket_part_blue
#        pose:
#          xyz: [-0.15, -0.2, 0.2]
#          rpy: [0, 0, '-pi/4']
      part_3:
        type: gear_part_blue
        pose:
          xyz: [0.15, -0.2, 0.2]
          rpy: [0, 0, 'pi/4']



belt_models:
  gasket_part_blue:
    10.0: #interval at which the object is spawned on the belt
      pose:
        xyz: [0.0, 4.3, 0.92]
        rpy: [0, 0, 'pi/2']


models_over_bins:
  bin1:
    models:
      pulley_part_red:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.45, 0.45, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2

models_over_shelves:
  shelf5:
    models:
      gasket_part_green:
        xyz_start: [1, -0.3, 0.0]
        xyz_end: [0., -0.4, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 4
        num_models_y: 1
      gear_part_blue:
        xyz_start: [1, 0.45, 0.0]
        xyz_end: [0., 0.45, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 4
        num_models_y: 1


#Faulty gripper
#drops:
#  drop_regions:
#    shipping_box_0_impeding:
#      frame: agv1::kit_tray_1
#      min:
#        xyz: [-0.3, -0.3, 0.0]
#      max:
#        xyz: [0.3, 0.3, 0.5]
#      destination:
#        xyz: [0.2, 0.3, 0.05]
#        rpy: [0, 0, 0.2]
#      product_type_to_drop: gasket_part_blue
#    shipping_box_0_impeding:
#      frame: agv2::kit_tray_2
#      min:
#        xyz: [-0.3, -0.3, 0.0]
#      max:
#        xyz: [0.3, 0.3, 0.5]
#      destination:
#        xyz: [0.2, 0.3, 0.05]
#        rpy: [0, 0, 0.2]
#      product_type_to_drop: gear_part_blue


#Faulty products
faulty_products:
  - pulley_part_red_1
  - pulley_part_red_2
  - gasket_part_green_1
  - gasket_part_blue_1
