#Moving Obstacle #5

#Number of orders: 2
#Number of shipments per order: 1
#Challenges:
#  -Interruption: Yes
#  -Drop parts: Yes
#  -Sensor blackout: Yes
#  -Part flipping: Yes
#  -Faulty parts: Yes
#  -Moving obstacle: Yes
#Containers
# -Belt: Yes
# -Bins: Optional
# -Shelf: Yes
#AGV
# -order_0:
#   -shipment_0: agv1
# -order_1:
#   -shipment_0: agv2
#Time limit: Yes

time_limit: 500

options:
  gazebo_state_logging: true
  insert_models_over_bins: true
  insert_models_over_shelves: true
  belt_population_cycles: 10 #How many objects to spawn in total
  spawn_extra_models: true
  model_type_aliases:
    order_part1: gasket_part_red
    order_part2: gasket_part_blue
    order_part3: pulley_part_red
    order_part3: pulley_part_blue

shelf_layout:
  row_1: ['base',0,'collar','pipe'] #shelves: 3, 4, 5
  row_2: ['pipe',0,'base','collar']   #shelves: 6, 7, 8
  row_3: ['base','collar',0,'pipe'] #shelves: 9, 10, 11

aisle_layout:
  person_1:
    location: -1.57
    start_time: 0.
    move_time: 9.
    wait_time: 7.
  person_2:
    location: -4.57
    start_time: 16.
    move_time: 9.
    wait_time: 7.


orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 1
    destinations: [agv1]
    products:
      part_0:
        type: pulley_part_blue
        pose:
          xyz: [0.1, 0.2, 0.2]
          rpy: ['pi', 0, 0]
      part_1:
        type: gasket_part_blue
        pose:
          xyz: [0.0, 0.0, 0.2]
          rpy: [0, 0, '-pi/4']
      part_2:
        type: gasket_part_red
        pose:
          xyz: [-0.15, 0.2, 0.2]
          rpy: [0, 0, '-pi/4']
  order_1:
    announcement_condition: time
    announcement_condition_value: 20.0
    shipment_count: 1
    destinations: [agv2]
    products:
#      part_0:
#        type: pulley_part_red
#        pose:
#          xyz: [0.1, 0.2, 0.2]
#          rpy: ['pi', 0, 0]
      part_1:
        type: gasket_part_red
        pose:
          xyz: [0.0, 0.0, 0.2]
          rpy: [0, 0, '-pi/4']
      part_2:
        type: gasket_part_blue
        pose:
          xyz: [-0.15, 0.2, 0.2]
          rpy: [0, 0, '-pi/4']


belt_models:
  pulley_part_red:
    8.0: #interval at which the object is spawned on the belt
      pose:
        xyz: [0.0, 4.3, 0.92]
        rpy: [0, 0, 'pi/2']


models_over_shelves:
  shelf2:
    models:
      gasket_part_red:
        xyz_start: [1, -0.45, 0.0]
        xyz_end: [0., -0.45, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 4
        num_models_y: 1
  shelf11:
    models:
      gasket_part_blue:
        xyz_start: [1, -0.45, 0.0]
        xyz_end: [0., -0.45, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 4
        num_models_y: 1
      pulley_part_blue:
        xyz_start: [1, 0.45, 0.0]
        xyz_end: [0., 0.45, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 4
        num_models_y: 1


#Faulty gripper
drops:
  drop_regions:
    shipping_box_0_impeding:
      frame: agv1::kit_tray_1
      min:
        xyz: [-0.3, -0.3, 0.0]
      max:
        xyz: [0.3, 0.3, 0.5]
      destination:
        xyz: [0.2, 0.3, 0.05]
        rpy: [0, 0, 0.2]
      product_type_to_drop: gasket_part_red
    shipping_box_0_impeding:
      frame: agv2::kit_tray_2
      min:
        xyz: [-0.3, -0.3, 0.0]
      max:
        xyz: [0.3, 0.3, 0.5]
      destination:
        xyz: [0.2, 0.3, 0.05]
        rpy: [0, 0, 0.2]
      product_type_to_drop: gasket_part_blue

sensor_blackout:
  product_count: 2 #sensor blackout triggered after 3rd product is placed
  duration: 50


#Faulty products
#faulty_products:
#  - pulley_part_red_2
#  - gasket_part_red_1
#  - gasket_part_red_2
